name: Django CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://devpro:devpro@postgres:5432/devpro
    
    # Service containers to run with `container-job`
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: devpro
          POSTGRES_PASSWORD: devpro
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9.6
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.1'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Run Pipenv
      run: |
        pipenv install -d
        # stop the build if there are Python syntax errors or undefined names

    - name: Setup Env
      run: |
        cp .env.example .env

    - name: Run Flake8
      run: |
        pipenv run flake8
        # python manage.py test

  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    needs: build
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
